FROM jupyter/base-notebook:38f518466042

LABEL maintainer="Lirongfan <lirongfan@orientsoft.cn>"

USER root

RUN apt-get update\
    # chinese localization
    && apt-get install -y fontconfig \
    ttf-mscorefonts-installer\
    texlive-xetex\
    latex-cjk-chinese\
    texlive-fonts-recommended\
    language-pack-zh-hans language-pack-zh-hans-base\
    make\
    && apt-get -y autoremove && apt-get -y autoclean\
    && rm -rf /var/lib/apt/lists/* 

COPY ./requirements.txt ./

RUN rm /opt/conda/conda-meta/pinned\
    && conda install -y -c conda-forge -c pytorch -c simpleitk --file requirements.txt \
    && conda install -c conda-forge jupyter_contrib_nbextensions babel autopep8

COPY ./requirements_pip.txt ./
RUN pip install -r requirements_pip.txt

ARG NB_USER="jovyan"
ARG NB_UID="1000"
ARG NB_GID="100"

ENV LC_ALL=zh_CN.UTF-8 
ENV LANG=zh_CN.UTF-8 
ENV LANGUAGE=zh_CN:zh:en_US:en
ENV ENV_NAME="base" 
ENV HOME=/home/$NB_USER 
ENV PRO_HOME=/home/$NB_USER/project/pro_face_detection
ENV PATH=$CONDA_DIR/bin:$PATH

WORKDIR $HOME
COPY ./files/ ./
COPY ./face-detection ${PRO_HOME}

RUN chown -R $NB_USER:$NB_GID ${PRO_HOME} \
    && mv $HOME/my_start.sh /usr/local/bin/my_start.sh \
    && bash -c '/bin/echo -e "y\n" | bash ./temporary/config.sh' \
    && bash ./compile.sh \
    && fix-permissions /home/$NB_USER

EXPOSE 8888
ENTRYPOINT ["bash"]
# CMD ["/usr/local/bin/my_start.sh"]
