FROM jupyter/base-notebook:38f518466042

LABEL maintainer="Lirongfan <lirongfan@orientsoft.cn>"

USER root

RUN apt-get update\
    # chinese localization
    && apt-get install -y fontconfig \
    ttf-mscorefonts-installer\
    texlive-xetex\
    latex-cjk-chinese\
    texlive-fonts-recommended\
    language-pack-zh-hans language-pack-zh-hans-base\
    make\
    && apt-get -y autoremove && apt-get -y autoclean\
    && rm -rf /var/lib/apt/lists/* 

RUN rm /opt/conda/conda-meta/pinned\
    && conda install -c conda-forge -c anaconda \
    jupyter_contrib_nbextensions \
    babel \
    autopep8 \
    nb_conda \
    matplotlib \
    cython

ARG NB_USER="jovyan"
ARG NB_UID="1000"
ARG NB_GID="100"

ENV LC_ALL=zh_CN.UTF-8 
ENV LANG=zh_CN.UTF-8 
ENV LANGUAGE=zh_CN:zh:en_US:en
ENV ENV_NAME="base" 
ENV HOME=/home/$NB_USER 
ENV PRO_HOME=/home/$NB_USER/project/pro_face_detection
ENV PATH=$CONDA_DIR/bin:$PATH

WORKDIR $HOME

COPY ./files/environment.yml ./
RUN conda env create -f environment.yml

COPY ./files/ ./
RUN bash env_fix.sh \
    && mv $HOME/my_start.sh /usr/local/bin/my_start.sh \
    && bash -c '/bin/echo -e "y\n" | bash ./temporary/config.sh' \
    && fix-permissions /home/$NB_USER \
    && conda clean --all -f -y\
    && rm -rf temporary env_fix.sh environment.yml work

EXPOSE 8888
ENTRYPOINT ["bash"]
CMD ["/usr/local/bin/my_start.sh"]
# COPY ./pro_face_detection ${PRO_HOME}
# COPY ./pro_face_detection ./